In [1]:
#NumPy Basics: Arrays and Vectorized Computation
import numpy as np
np.random.seed(12345) 
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6)) 
np.set_printoptions(precision=4, suppress=True)

In [2]:
import numpy as np
my_arr = np.arange(1000000) 
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2 
%time for _ in range(10): my_list2 = [x * 2 for x in my_list] 


Wall time: 23.9 ms
Wall time: 810 ms


In [5]:

# Generate some random data
data = np.random.randn(2, 3) 
data 

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

In [6]:
data * 10
data + data 

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

In [7]:
data.shape 
data.dtype 


dtype('float64')

In [8]:
data1 = [6, 7.5, 8, 0, 1] 
arr1 = np.array(data1) 
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 
arr2 = np.array(data2) 
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim 
arr2.shape 

(2, 4)

In [11]:
arr1.dtype 
arr2.dtype 


dtype('int32')

In [12]:
np.zeros(10) 
np.zeros((3, 6)) 
np.empty((2, 3, 2))

array([[[1.3210e-311, 3.0138e-322],
        [0.0000e+000, 0.0000e+000],
        [1.1034e-312, 1.1610e-028]],

       [[3.7338e+174, 2.1342e+161],
        [6.3230e+233, 2.5903e-144],
        [4.8241e+228, 1.0472e-142]]])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64) 
arr2 = np.array([1, 2, 3], dtype=np.int32) 
arr1.dtype 
arr2.dtype

dtype('int32')

In [15]:
arr = np.array([1, 2, 3, 4, 5]) 
arr.dtype 
float_arr = arr.astype(np.float64) 
float_arr.dtype 

dtype('float64')

In [16]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1]) 
arr 
arr.astype(np.int32) 

array([ 3, -1, -2,  0, 12, 10])

In [17]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_) 
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [18]:
int_array = np.arange(10) 
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64) 
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
empty_uint32 = np.empty(8, dtype='u4') 
empty_uint32 

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [20]:
#Arithmetic with NumPy Arrays 
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr 
arr * arr 
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]]) 
arr2 
arr2 > arr 

array([[False,  True, False],
       [ True, False,  True]])

In [22]:
#Basic Indexing and Slicing 
arr = np.arange(10) 
arr 
arr[5] 
arr[5:8] 
arr[5:8] = 12
arr 


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
arr_slice = arr[5:8] 
arr_slice

array([12, 12, 12])

In [24]:
arr_slice[1] = 12345
arr 

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [25]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
arr2d[2] 

array([7, 8, 9])

In [28]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) 
arr3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
old_values = arr3d[0].copy() 
arr3d[0] = 42
arr3d 
arr3d[0] = old_values 
arr3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
arr3d[1, 0] 

array([7, 8, 9])

In [32]:
x = arr3d[1] 
x 
x[0]

array([7, 8, 9])

In [33]:
#Indexing with slices 
arr 
arr[1:6]


array([ 1,  2,  3,  4, 64])

In [34]:
arr2d 
arr2d[:2] 

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr2d[:2, 1:] 


array([[2, 3],
       [5, 6]])

In [36]:
arr2d[1, :2] 

array([4, 5])

In [37]:
arr2d[:2, 2] 

array([3, 6])

In [38]:
arr2d[:, :1] 

array([[1],
       [4],
       [7]])

In [39]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [40]:
#Boolean Indexing 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4) 
names 
data

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

In [41]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [42]:
data[names == 'Bob'] 

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.669 , -0.4386, -0.5397,  0.477 ]])

In [43]:
data[names == 'Bob', 2:] 
data[names == 'Bob', 3] 

array([1.2464, 0.477 ])

In [44]:
names != 'Bob'
data[~(names == 'Bob')] 

array([[ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

In [45]:
cond = names == 'Bob'
data[~cond] 

array([[ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

In [46]:
mask = (names == 'Bob') | (names == 'Will') 
mask 
data[mask] 

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241]])

In [47]:
data[data < 0] = 0
data 


array([[0.0929, 0.2817, 0.769 , 1.2464],
       [1.0072, 0.    , 0.275 , 0.2289],
       [1.3529, 0.8864, 0.    , 0.    ],
       [1.669 , 0.    , 0.    , 0.477 ],
       [3.2489, 0.    , 0.    , 0.1241],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

In [48]:
data[names != 'Joe'] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [1.0072, 0.    , 0.275 , 0.2289],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

In [49]:
#Fancy Indexing
arr = np.empty((8, 4)) 
for i in range(8): 
 arr[i] = i 
arr 


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [50]:
arr[[4, 3, 0, 6]] 


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [51]:
arr[[-3, -5, -7]] 

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [52]:
arr = np.arange(32).reshape((8, 4)) 
arr 
arr[[1, 5, 7, 2], [0, 3, 1, 2]] 

array([ 4, 23, 29, 10])

In [53]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] 


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [54]:
#Transposing Arrays and Swapping Axes
arr = np.arange(15).reshape((3, 5)) 
arr 
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [55]:
arr = np.random.randn(6, 3) 
arr 
np.dot(arr.T, arr) 

array([[ 9.2291,  0.9394,  4.948 ],
       [ 0.9394,  3.7662, -1.3622],
       [ 4.948 , -1.3622,  4.3437]])

In [56]:
arr = np.arange(16).reshape((2, 2, 4)) 
arr 
arr.transpose((1, 0, 2)) 

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [57]:
arr 
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [58]:
#Universal Functions: Fast Element-Wise Array Functions 
arr = np.arange(10) 
arr 
np.sqrt(arr) 
np.exp(arr) 

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

In [59]:
x = np.random.randn(8) 
y = np.random.randn(8) 
x 
y 
np.maximum(x, y) 

array([ 0.8626,  1.0048,  1.3272,  0.6702,  0.853 ,  0.0222,  0.7584,
       -0.6605])

In [60]:
arr = np.random.randn(7) * 5
arr 
remainder, whole_part = np.modf(arr) 
remainder 
whole_part 

array([-3., -6., -6.,  5.,  3.,  3.,  5.])

In [62]:
arr 
np.sqrt(arr) 
np.sqrt(arr, arr) 
arr 
 

C:\Users\exam\AppData\Local\Temp/ipykernel_5564/373961122.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)
C:\Users\exam\AppData\Local\Temp/ipykernel_5564/373961122.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([   nan,    nan,    nan, 2.318 , 1.9022, 1.8574, 2.2378])

In [63]:
#Mathematical and Statistical Methods 
arr = np.random.randn(5, 4) 
arr 
arr.mean() 
np.mean(arr) 
arr.sum() 

5.3396379923748025

In [64]:
arr.mean(axis=1) 
arr.sum(axis=0) 

array([ 3.1735,  0.1933,  2.6621, -0.6892])

In [65]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7]) 
arr.cumsum() 

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [66]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) 
arr 
arr.cumsum(axis=0) 
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [67]:
#Methods for Boolean Arrays 
arr = np.random.randn(100) 
(arr > 0).sum() 

43

In [68]:
bools = np.array([False, False, True, False]) 
bools.any() 
bools.all() 

False

In [69]:
#Sorting
arr = np.random.randn(6) 
arr 
arr.sort() 
arr 

array([-1.4134, -1.0209,  0.2523,  0.911 ,  1.1275,  1.2966])

In [70]:
arr = np.random.randn(5, 3) 
arr 
arr.sort(1) 
arr

array([[-0.5774, -0.5684,  0.3094],
       [-2.6444, -1.1686, -0.825 ],
       [-0.7519, -0.153 , -0.1326],
       [-0.4938,  0.6095,  1.4573],
       [-0.1357,  1.24  ,  1.43  ]])

In [71]:
large_arr = np.random.randn(1000) 
large_arr.sort() 
large_arr[int(0.05 * len(large_arr))]


-1.5311513550102103

In [72]:
#Unique and Other Set Logic 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
np.unique(names) 
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4]) 
np.unique(ints) 

array([1, 2, 3, 4])

In [73]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [74]:
values = np.array([6, 0, 0, 3, 2, 5, 6]) 
np.in1d(values, [2, 3, 6]) 


array([ True, False, False,  True,  True, False,  True])